#!/bin/sh
#
# bathroomd: Turns the PCM volume off if the light goes out
#
# Useful for putting your Squeezebox in your bathroom.
#
# (c) Enno Luebbers <luebbers_at_reconos.de>
#
# See README for details.

#
# Constants
#
CHECK_INTERVAL=1
AMBIENT=/sys/class/i2c-adapter/i2c-1/1-0010/ambient
THRESHOLD_LO=300
THRESHOLD_HI=500
MUTE="amixer sset PCM 0"
UNMUTE="amixer sset PCM 255"

# Unmute first (if last daemon run was interrupted while mute)
$UNMUTE > /dev/null
state="UNMUTE"

# loop forever
while /bin/true; do

	# sleep a bit
	sleep $CHECK_INTERVAL

	# read sensor value and truncate newline
	val=`cat $AMBIENT | tr "\n" " "`
	
	# if verbose (option -v), print value
	if [ "$1" == "-v" ]; then
		echo -n "read val: "
		echo $val
	fi
	
	# unmute if bright enough	
	if [ $val -lt $THRESHOLD_LO ]; then
		if [ $state == "MUTE" ]; then
			$UNMUTE > /dev/null
			state="UNMUTE"
		fi
	fi
	# mute if not bright enough
	if [ $val -gt $THRESHOLD_HI ]; then
		if [ $state == "UNMUTE" ]; then
			$MUTE > /dev/null
			state="MUTE"
		fi
	fi
	
done

